from PIL import Image
from PIL import ImageFilter
from PIL import ImageChops
import matplotlib.pyplot as plt

obraz = Image.open("obraz.jpg")


# zad 1
def filtruj(obraz, kernel, scale):
    im1 = obraz.copy()
    im_pix = obraz.load()
    im1_pix = im1.load()
    w, h = obraz.size
    k = len(kernel)
    d = int(k / 2)
    for x in range(d, w - d):
        for y in range(d, h - d):
            temp = [0, 0, 0]
            for a in range(k):
                for b in range(k):
                    xn = x + a - d
                    yn = y + b - d
                    pixel = im_pix[xn, yn]
                    temp[0] += pixel[0] * kernel[a][b]
                    temp[1] += pixel[1] * kernel[a][b]
                    temp[2] += pixel[2] * kernel[a][b]
            im1_pix[x, y] = (int(temp[0] / scale), int(temp[1] / scale), int(temp[2] / scale))
    return im1


kern = [[-1, -1, -1], [-1, 8, -1], [-1, -1, -1]]
skala = 1
fi = filtruj(obraz, kern, skala)

fi.show()

# zad 2
imB = obraz.filter(ImageFilter.BLUR)
print(ImageFilter.BLUR.filterargs)
kern1 = [[1, 1, 1, 1, 1], [1, 0, 0, 0, 1], [1, 0, 0, 0, 1], [1, 0, 0, 0, 1], [1, 1, 1, 1, 1]]
imB1 = filtruj(obraz, kern1, 16)
diffB = ImageChops.difference(imB, imB1)
plt.figure(figsize=(32, 16))
plt.subplot(2, 2, 1)
plt.title("obraz wejsciowy")
plt.imshow(obraz)
plt.axis('off')
plt.subplot(2, 2, 2)
plt.title("filtr BLUR")
plt.imshow(imB)
plt.axis('off')
plt.subplot(2, 2, 3)
plt.title("filtr BLUR - funkcja filtruj")
plt.imshow(imB1)
plt.axis('off')
plt.subplot(2, 2, 4)
plt.title("roznica")
plt.imshow(diffB)
plt.axis('off')
plt.subplots_adjust(wspace=0.05, hspace=0.05)
plt.tight_layout()
plt.savefig("fig1.png")
plt.show()

# zad 3
imL = obraz.convert('L')
imL1 = imL.filter(ImageFilter.EMBOSS)
print(ImageFilter.EMBOSS.filterargs)
ImageFilter.EMBOSS.filterargs = ((3, 3), 1, 128, (-1, 0, 1, -2, 0, 2, -1, 0, 1))
imSOB = imL.filter(ImageFilter.EMBOSS)
ImageFilter.EMBOSS.filterargs = ((3, 3), 1, 128, (-1, -2, -1, 0, 0, 0, 1, 2, 1))
imSOB2 = imL.filter(ImageFilter.EMBOSS)
plt.figure(figsize=(32, 16))
plt.subplot(2, 2, 1)
plt.title("obraz w trybie L")
plt.imshow(imL)
plt.axis('off')
plt.subplot(2, 2, 2)
plt.title("filtr EMBOSS")
plt.imshow(imL1)
plt.axis('off')
plt.subplot(2, 2, 3)
plt.title("filtr SOBEL1")
plt.imshow(imSOB)
plt.axis('off')
plt.subplot(2, 2, 4)
plt.title("filtr SOBEL2")
plt.imshow(imSOB2)
plt.axis('off')
plt.subplots_adjust(wspace=0.05, hspace=0.05)
plt.tight_layout()
plt.savefig("fig2.png")
plt.show()

# zad 4
fil2 = obraz.filter(ImageFilter.DETAIL)
fil4 = obraz.filter(ImageFilter.EDGE_ENHANCE_MORE)
fil6 = obraz.filter(ImageFilter.SHARPEN)
fil8 = obraz.filter(ImageFilter.SMOOTH_MORE)
diff2 = ImageChops.difference(obraz, fil2)
diff4 = ImageChops.difference(obraz, fil4)
diff6 = ImageChops.difference(obraz, fil6)
diff8 = ImageChops.difference(obraz, fil8)
plt.figure(figsize=(32, 16))
plt.subplot(4, 2, 1)
plt.title("filtr DETAIL")
plt.imshow(fil2)
plt.axis('off')
plt.subplot(4, 2, 2)
plt.title("roznica")
plt.imshow(diff2)
plt.axis('off')
plt.subplot(4, 2, 3)
plt.title("filtr EDGE_ENHANCE_MORE")
plt.imshow(fil4)
plt.axis('off')
plt.subplot(4, 2, 4)
plt.title("roznica")
plt.imshow(diff4)
plt.axis('off')
plt.subplot(4, 2, 5)
plt.title("filtr SHARPEN")
plt.imshow(fil6)
plt.axis('off')
plt.subplot(4, 2, 6)
plt.title("roznica")
plt.imshow(diff6)
plt.axis('off')
plt.subplot(4, 2, 7)
plt.title("filtr SMOOTH_MORE")
plt.imshow(fil8)
plt.axis('off')
plt.subplot(4, 2, 8)
plt.title("roznica")
plt.imshow(diff8)
plt.axis('off')
plt.subplots_adjust(wspace=0.05, hspace=0.05)
plt.tight_layout()
plt.savefig("fig3.png")
plt.show()

# zad 5
fil12 = obraz.filter(ImageFilter.GaussianBlur(radius=3))
fil13 = obraz.filter(ImageFilter.UnsharpMask(radius=2, percent=125, threshold=4))
fil16 = obraz.filter(ImageFilter.MedianFilter(size=3))
fil17 = obraz.filter(ImageFilter.MinFilter(size=3))
fil18 = obraz.filter(ImageFilter.MaxFilter(size=3))
diff12 = ImageChops.difference(obraz, fil12)
diff13 = ImageChops.difference(obraz, fil13)
diff16 = ImageChops.difference(obraz, fil16)
diff17 = ImageChops.difference(obraz, fil17)
diff18 = ImageChops.difference(obraz, fil18)
plt.figure(figsize=(32, 16))
plt.subplot(5, 2, 1)
plt.title("filtr GaussianBlur, radius=3")
plt.imshow(fil12)
plt.axis('off')
plt.subplot(5, 2, 2)
plt.title("roznica")
plt.imshow(diff12)
plt.axis('off')
plt.subplot(5, 2, 3)
plt.title("filtr UnsharpMask, radius=2, percent=125, threshold=4")
plt.imshow(fil13)
plt.axis('off')
plt.subplot(5, 2, 4)
plt.title("roznica")
plt.imshow(diff13)
plt.axis('off')
plt.subplot(5, 2, 5)
plt.title("filtr MedianFilter, size=3")
plt.imshow(fil16)
plt.axis('off')
plt.subplot(5, 2, 6)
plt.title("roznica")
plt.imshow(diff16)
plt.axis('off')
plt.subplot(5, 2, 7)
plt.title("filtr MinFilter, size=3")
plt.imshow(fil17)
plt.axis('off')
plt.subplot(5, 2, 8)
plt.title("roznica")
plt.imshow(diff17)
plt.axis('off')
plt.subplot(5, 2, 9)
plt.title("filtr MaxFilter, size=3")
plt.imshow(fil18)
plt.axis('off')
plt.subplot(5, 2, 10)
plt.title("roznica")
plt.imshow(diff18)
plt.axis('off')
plt.subplots_adjust(wspace=0.05, hspace=0.05)
plt.tight_layout()
plt.savefig("fig4.png")
plt.show()
