from PIL import Image
import numpy as np
from PIL import ImageChops
import matplotlib.pyplot as plt

# zad 2
im1 = Image.open('obraz.jpg')
h, w = im1.size
T = np.array(im1)
t_r = T[:, :, 0]
t_g = T[:, :, 1]
t_b = T[:, :, 2]
im_r = Image.fromarray(t_r)
im_g = Image.fromarray(t_g)
im_b = Image.fromarray(t_b)

im2 = Image.merge('RGB', (im_r, im_g, im_b))
diff_im = ImageChops.difference(im1, im2)

plt.figure(figsize=(32, 16))
plt.subplot(3,1,1)
plt.imshow(im1)
plt.axis('off')
plt.subplot(3,1,2)
plt.imshow(im2)
plt.axis('off')
plt.subplot(3,1,3)
plt.imshow(diff_im)
plt.axis('off')
plt.subplots_adjust(wspace=0.05, hspace=0.05)
plt.savefig("fig1.png")
plt.show()

# zad 3
r, g, b = im1.split()
im3 = Image.merge('RGB', (g, b, r))
im3.save("im3.jpg")
im3.save("im3.png")
im3j = Image.open("im3.jpg")
im3p = Image.open("im3.png")
diff_im3 = ImageChops.difference(im3j, im3p)
plt.figure(figsize=(32, 16))
plt.subplot(3,1,1)
plt.imshow(im3j)
plt.axis('off')
plt.subplot(3,1,2)
plt.imshow(im3p)
plt.axis('off')
plt.subplot(3,1,3)
plt.imshow(diff_im3)
plt.axis('off')
plt.subplots_adjust(wspace=0.05, hspace=0.05)
plt.savefig("fig2.png")
plt.show()

# zad 4
ob1_1j = Image.open("obraz1_1.jpg")
ob1_1p = Image.open("obraz1_1.png")
ob1_1Nj = Image.open("obraz1_1N.jpg")
ob1_1Np = Image.open("obraz1_1N.png")
ob1_2j = Image.open("obraz1_2.jpg")
ob1_2p = Image.open("obraz1_2.png")
ob1_2Nj = Image.open("obraz1_2N.jpg")
ob1_2Np = Image.open("obraz1_2N.png")
diffob1_1 = ImageChops.difference(ob1_1j, ob1_1p)
diffob1_1N = ImageChops.difference(ob1_1Nj, ob1_1Np)
diffob1_2 = ImageChops.difference(ob1_2j, ob1_2p)
diffob1_2N = ImageChops.difference(ob1_2Nj, ob1_2Np)
plt.figure(figsize=(32, 16))
plt.subplot(4,3,1)
plt.imshow(ob1_1j, 'gray')
plt.axis('off')
plt.subplot(4,3,2)
plt.imshow(ob1_1p, 'gray')
plt.axis('off')
plt.subplot(4,3,3)
plt.imshow(diffob1_1, 'gray')
plt.axis('off')
plt.subplot(4,3,4)
plt.imshow(ob1_1Nj, 'gray')
plt.axis('off')
plt.subplot(4,3,5)
plt.imshow(ob1_1Np, 'gray')
plt.axis('off')
plt.subplot(4,3,6)
plt.imshow(diffob1_1N, 'gray')
plt.axis('off')
plt.subplot(4,3,7)
plt.imshow(ob1_2j, 'gray')
plt.axis('off')
plt.subplot(4,3,8)
plt.imshow(ob1_2p, 'gray')
plt.axis('off')
plt.subplot(4,3,9)
plt.imshow(diffob1_2, 'gray')
plt.axis('off')
plt.subplot(4,3,10)
plt.imshow(ob1_2Nj, 'gray')
plt.axis('off')
plt.subplot(4,3,11)
plt.imshow(ob1_2Np, 'gray')
plt.axis('off')
plt.subplot(4,3,12)
plt.imshow(diffob1_2N, 'gray')
plt.axis('off')
plt.subplots_adjust(wspace=0.05, hspace=0.05)
plt.savefig("fig3.png")
plt.show()